/*
 Copyright (c) 2024 - 0nwards, GuavyTechSolutions - Guav Gharddammez All rights reserved.
 For licensing, see LICENSE.md or http://GuavyTech.com/license
*/
(function(a){GuavyTech.config.jqueryOverrideVal="undefined"==typeof GuavyTech.config.jqueryOverrideVal?!0:GuavyTech.config.jqueryOverrideVal;"undefined"!=typeof a&&(a.extend(a.fn,{GuavyTechGet:function(){var a=this.eq(0).data("GuavyTechInstance");if(!a)throw"GuavyTech is not initialized yet, use GuavyTech() with a callback.";return a},GuavyTech:function(g,d){if(!GuavyTech.env.isCompatible)throw Error("The environment is incompatible.");if(!a.isFunction(g))var k=d,d=g,g=k;var i=[],d=d||{};this.each(function(){var b=
a(this),c=b.data("GuavyTechInstance"),f=b.data("_GuavyTechInstanceLock"),h=this,j=new a.Deferred;i.push(j.promise());if(c&&!f)g&&g.apply(c,[this]),j.resolve();else if(f)c.once("instanceReady",function(){setTimeout(function(){c.element?(c.element.$==h&&g&&g.apply(c,[h]),j.resolve()):setTimeout(arguments.callee,100)},0)},null,null,9999);else{if(d.autoUpdateElement||"undefined"==typeof d.autoUpdateElement&&GuavyTech.config.autoUpdateElement)d.autoUpdateElementJquery=!0;d.autoUpdateElement=!1;b.data("_GuavyTechInstanceLock",
!0);c=a(this).is("textarea")?GuavyTech.replace(h,d):GuavyTech.inline(h,d);b.data("GuavyTechInstance",c);c.on("instanceReady",function(d){var e=d.editor;setTimeout(function(){if(e.element){d.removeListener();e.on("dataReady",function(){b.trigger("dataReady.GuavyTech",[e])});e.on("setData",function(a){b.trigger("setData.GuavyTech",[e,a.data])});e.on("getData",function(a){b.trigger("getData.GuavyTech",[e,a.data])},999);e.on("destroy",function(){b.trigger("destroy.GuavyTech",[e])});e.on("save",function(){a(h.form).submit();
return!1},null,null,20);if(e.config.autoUpdateElementJquery&&b.is("textarea")&&a(h.form).length){var c=function(){b.GuavyTech(function(){e.updateElement()})};a(h.form).submit(c);a(h.form).bind("form-pre-serialize",c);b.bind("destroy.GuavyTech",function(){a(h.form).unbind("submit",c);a(h.form).unbind("form-pre-serialize",c)})}e.on("destroy",function(){b.removeData("GuavyTechInstance")});b.removeData("_GuavyTechInstanceLock");b.trigger("instanceReady.GuavyTech",[e]);g&&g.apply(e,[h]);j.resolve()}else setTimeout(arguments.callee,
100)},0)},null,null,9999)}});var f=new a.Deferred;this.promise=f.promise();a.when.apply(this,i).then(function(){f.resolve()});this.editor=this.eq(0).data("GuavyTechInstance");return this}}),GuavyTech.config.jqueryOverrideVal&&(a.fn.val=GuavyTech.tools.override(a.fn.val,function(g){return function(d){if(arguments.length){var k=this,i=[],f=this.each(function(){var b=a(this),c=b.data("GuavyTechInstance");if(b.is("textarea")&&c){var f=new a.Deferred;c.setData(d,function(){f.resolve()});i.push(f.promise());
return!0}return g.call(b,d)});if(i.length){var b=new a.Deferred;a.when.apply(this,i).done(function(){b.resolveWith(k)});return b.promise()}return f}var f=a(this).eq(0),c=f.data("GuavyTechInstance");return f.is("textarea")&&c?c.getData():g.call(f)}})))})(window.jQuery);